### PR TITLE
fix: unbreak master tests and keep betas off the latest dist-tag

### PR DESCRIPTION
**Pull request by bobvanoorschot**
## Why

Master is red. `src/__tests__/website.test.tsx` arrived with #324 (IIFE website build) while #499 removed Apollo Client; the two merged in parallel, so the test still mocks `@apollo/client` and `../_lib/gql`, which no longer exist:

```
FAIL src/__tests__/website.test.tsx
  ● Test suite failed to run
    Cannot find module '@apollo/client' from 'src/__tests__/website.test.tsx'
```

691 tests pass; only that suite fails to load. This also blocks `Release npm package`, whose `build` job runs `npm test`.

Separately, the publish job ran a bare `npm publish`. Any prerelease version would have taken the `latest` dist-tag, so a plain `npm install bukazu-portal-react` would hand consumers a beta instead of 3.9.0. (The existing `4.0.0-beta.x` releases avoided this only because they were published by hand.)

## What

- Drop the `@apollo/client` and `../_lib/gql` mocks from `website.test.tsx` — `index.tsx` imports neither any more.
- Derive the npm dist-tag from the version's prerelease label: `4.0.0-beta.3` publishes as `--tag beta`, stable versions still publish as `latest`.
- Mark prerelease GitHub releases with `prerelease: true`.

## Testing

Jest cannot run on this machine (node 18 locally, repo needs 24 — Babel 8 is ESM-only), so CI is the check here. Expecting `Tests` green on 24.x.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

File: .github/workflows/npm-publish.yml [hunk 1]
```diff
@@ -64,7 +64,15 @@ jobs:
         run: |
           echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
       - run: npm run build
-      - run: npm publish
+      - name: Publish to npm
+        run: |
+          if [[ "$VERSION" == *-* ]]; then
```
[the remark this answers is not in the document]
Comment (bobvanoorschot) [reply .github/workflows/npm-publish.yml:69]: Checked this — the quoting is fine, and the step is unchanged by this PR.

Bash starts a fresh quoting context inside `$( )`, so the inner `"require('./package.json').version"` is not a terminator for the outer quotes. Running the exact line locally:

```
$ echo "VERSION=$(node -p "require('./package.json').version")"
VERSION=4.0.0-beta.1
```

and feeding that through the new publish logic yields `npm publish --tag beta`, as intended.

The `Get version` step also predates this PR and has shipped releases: run 25152819536 ("chore: Bump version to v3.9.0", 2026-04-30) succeeded and published 3.9.0, and the `v3.9.0` release exists.

On the shell suggestion: `run:` steps on Linux runners already default to bash, so `[[ ... ]]` and `${VERSION#*-}` work as written and an explicit `shell: bash` would be a no-op.

No change needed.
